/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedTaskCenterRouteImport } from './routes/_authenticated/task-center'
import { Route as ApiActionCenterRouteImport } from './routes/api/action-center'
import { Route as ApiAttritionRouteImport } from './routes/api/attrition'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPerformanceRouteImport } from './routes/api/performance'
import { Route as ApiScenarioRouteImport } from './routes/api/scenario'
import { Route as PipelineHeadcountRouteImport } from './routes/pipeline/headcount'
import { Route as AuthenticatedActionCenterActionIdRouteImport } from './routes/_authenticated/action-center.$actionId'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance.index'
import { Route as AuthenticatedAttendanceViewRouteImport } from './routes/_authenticated/attendance.$view'
import { Route as AuthenticatedEmployeeEmployeeIdRouteImport } from './routes/_authenticated/employee.$employeeId'
import { Route as ApiAuthActionRouteImport } from './routes/api/auth.$action'
import { Route as ApiPipelineHeadcountRouteImport } from './routes/api/pipeline/headcount'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskCenterRoute = AuthenticatedTaskCenterRouteImport.update({
  id: '/task-center',
  path: '/task-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiActionCenterRoute = ApiActionCenterRouteImport.update({
  id: '/api/action-center',
  path: '/api/action-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttritionRoute = ApiAttritionRouteImport.update({
  id: '/api/attrition',
  path: '/api/attrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerformanceRoute = ApiPerformanceRouteImport.update({
  id: '/api/performance',
  path: '/api/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScenarioRoute = ApiScenarioRouteImport.update({
  id: '/api/scenario',
  path: '/api/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineHeadcountRoute = PipelineHeadcountRouteImport.update({
  id: '/pipeline/headcount',
  path: '/pipeline/headcount',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActionCenterActionIdRoute =
  AuthenticatedActionCenterActionIdRouteImport.update({
    id: '/action-center/$actionId',
    path: '/action-center/$actionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceViewRoute =
  AuthenticatedAttendanceViewRouteImport.update({
    id: '/attendance/$view',
    path: '/attendance/$view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeeEmployeeIdRoute =
  AuthenticatedEmployeeEmployeeIdRouteImport.update({
    id: '/employee/$employeeId',
    path: '/employee/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthActionRoute = ApiAuthActionRouteImport.update({
  id: '/api/auth/$action',
  path: '/api/auth/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineHeadcountRoute = ApiPipelineHeadcountRouteImport.update({
  id: '/api/pipeline/headcount',
  path: '/api/pipeline/headcount',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/task-center': typeof AuthenticatedTaskCenterRoute
  '/api/action-center': typeof ApiActionCenterRoute
  '/api/attrition': typeof ApiAttritionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/performance': typeof ApiPerformanceRoute
  '/api/scenario': typeof ApiScenarioRoute
  '/pipeline/headcount': typeof PipelineHeadcountRoute
  '/action-center/$actionId': typeof AuthenticatedActionCenterActionIdRoute
  '/attendance/$view': typeof AuthenticatedAttendanceViewRoute
  '/employee/$employeeId': typeof AuthenticatedEmployeeEmployeeIdRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/pipeline/headcount': typeof ApiPipelineHeadcountRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/task-center': typeof AuthenticatedTaskCenterRoute
  '/api/action-center': typeof ApiActionCenterRoute
  '/api/attrition': typeof ApiAttritionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/performance': typeof ApiPerformanceRoute
  '/api/scenario': typeof ApiScenarioRoute
  '/pipeline/headcount': typeof PipelineHeadcountRoute
  '/': typeof AuthenticatedIndexRoute
  '/action-center/$actionId': typeof AuthenticatedActionCenterActionIdRoute
  '/attendance/$view': typeof AuthenticatedAttendanceViewRoute
  '/employee/$employeeId': typeof AuthenticatedEmployeeEmployeeIdRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/pipeline/headcount': typeof ApiPipelineHeadcountRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/task-center': typeof AuthenticatedTaskCenterRoute
  '/api/action-center': typeof ApiActionCenterRoute
  '/api/attrition': typeof ApiAttritionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/performance': typeof ApiPerformanceRoute
  '/api/scenario': typeof ApiScenarioRoute
  '/pipeline/headcount': typeof PipelineHeadcountRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/action-center/$actionId': typeof AuthenticatedActionCenterActionIdRoute
  '/_authenticated/attendance/$view': typeof AuthenticatedAttendanceViewRoute
  '/_authenticated/employee/$employeeId': typeof AuthenticatedEmployeeEmployeeIdRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/pipeline/headcount': typeof ApiPipelineHeadcountRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/chatbot'
    | '/employees'
    | '/task-center'
    | '/api/action-center'
    | '/api/attrition'
    | '/api/chat'
    | '/api/performance'
    | '/api/scenario'
    | '/pipeline/headcount'
    | '/action-center/$actionId'
    | '/attendance/$view'
    | '/employee/$employeeId'
    | '/api/auth/$action'
    | '/api/pipeline/headcount'
    | '/attendance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/chatbot'
    | '/employees'
    | '/task-center'
    | '/api/action-center'
    | '/api/attrition'
    | '/api/chat'
    | '/api/performance'
    | '/api/scenario'
    | '/pipeline/headcount'
    | '/'
    | '/action-center/$actionId'
    | '/attendance/$view'
    | '/employee/$employeeId'
    | '/api/auth/$action'
    | '/api/pipeline/headcount'
    | '/attendance'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/chatbot'
    | '/_authenticated/employees'
    | '/_authenticated/task-center'
    | '/api/action-center'
    | '/api/attrition'
    | '/api/chat'
    | '/api/performance'
    | '/api/scenario'
    | '/pipeline/headcount'
    | '/_authenticated/'
    | '/_authenticated/action-center/$actionId'
    | '/_authenticated/attendance/$view'
    | '/_authenticated/employee/$employeeId'
    | '/api/auth/$action'
    | '/api/pipeline/headcount'
    | '/_authenticated/attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckEmailRoute: typeof CheckEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiActionCenterRoute: typeof ApiActionCenterRoute
  ApiAttritionRoute: typeof ApiAttritionRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPerformanceRoute: typeof ApiPerformanceRoute
  ApiScenarioRoute: typeof ApiScenarioRoute
  PipelineHeadcountRoute: typeof PipelineHeadcountRoute
  ApiAuthActionRoute: typeof ApiAuthActionRoute
  ApiPipelineHeadcountRoute: typeof ApiPipelineHeadcountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-center': {
      id: '/_authenticated/task-center'
      path: '/task-center'
      fullPath: '/task-center'
      preLoaderRoute: typeof AuthenticatedTaskCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/action-center': {
      id: '/api/action-center'
      path: '/api/action-center'
      fullPath: '/api/action-center'
      preLoaderRoute: typeof ApiActionCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attrition': {
      id: '/api/attrition'
      path: '/api/attrition'
      fullPath: '/api/attrition'
      preLoaderRoute: typeof ApiAttritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/performance': {
      id: '/api/performance'
      path: '/api/performance'
      fullPath: '/api/performance'
      preLoaderRoute: typeof ApiPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenario': {
      id: '/api/scenario'
      path: '/api/scenario'
      fullPath: '/api/scenario'
      preLoaderRoute: typeof ApiScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/headcount': {
      id: '/pipeline/headcount'
      path: '/pipeline/headcount'
      fullPath: '/pipeline/headcount'
      preLoaderRoute: typeof PipelineHeadcountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/action-center/$actionId': {
      id: '/_authenticated/action-center/$actionId'
      path: '/action-center/$actionId'
      fullPath: '/action-center/$actionId'
      preLoaderRoute: typeof AuthenticatedActionCenterActionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/$view': {
      id: '/_authenticated/attendance/$view'
      path: '/attendance/$view'
      fullPath: '/attendance/$view'
      preLoaderRoute: typeof AuthenticatedAttendanceViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee/$employeeId': {
      id: '/_authenticated/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof AuthenticatedEmployeeEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$action': {
      id: '/api/auth/$action'
      path: '/api/auth/$action'
      fullPath: '/api/auth/$action'
      preLoaderRoute: typeof ApiAuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/headcount': {
      id: '/api/pipeline/headcount'
      path: '/api/pipeline/headcount'
      fullPath: '/api/pipeline/headcount'
      preLoaderRoute: typeof ApiPipelineHeadcountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedTaskCenterRoute: typeof AuthenticatedTaskCenterRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActionCenterActionIdRoute: typeof AuthenticatedActionCenterActionIdRoute
  AuthenticatedAttendanceViewRoute: typeof AuthenticatedAttendanceViewRoute
  AuthenticatedEmployeeEmployeeIdRoute: typeof AuthenticatedEmployeeEmployeeIdRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedTaskCenterRoute: AuthenticatedTaskCenterRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActionCenterActionIdRoute:
    AuthenticatedActionCenterActionIdRoute,
  AuthenticatedAttendanceViewRoute: AuthenticatedAttendanceViewRoute,
  AuthenticatedEmployeeEmployeeIdRoute: AuthenticatedEmployeeEmployeeIdRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckEmailRoute: CheckEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiActionCenterRoute: ApiActionCenterRoute,
  ApiAttritionRoute: ApiAttritionRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPerformanceRoute: ApiPerformanceRoute,
  ApiScenarioRoute: ApiScenarioRoute,
  PipelineHeadcountRoute: PipelineHeadcountRoute,
  ApiAuthActionRoute: ApiAuthActionRoute,
  ApiPipelineHeadcountRoute: ApiPipelineHeadcountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
